### ISSUE TITLE
panick FailedParsingRemainder

### ISSUE THREAD

**Issue by friedger** [lgalabru/clarity-lsp#10]
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { err: FailedParsingRemainder("\'ST12)\n(define-constant seller \'ST)\n(define-constant escrow \....

**Comment by lgalabru** [comment]
Thank you for reporting this issue @friedger!
This issue is being addressed with the latest release (2.11) available on visual studio marketplace.
Changelog available here: https://github.com/lgalabru/clarity-lsp/compare/2020-04-06...2020-04-07
