### ISSUE TITLE
color highlighting does not show up VS-Code or Gitpod.io

### ISSUE THREAD

**Issue by fluidvoice** [lgalabru/clarity-lsp#13]
Installing this LSP extension in both VS-Code v1.44.2 on my linux desktop and in [gitpod.io](gitpod.io) web IDE:
https://gitpod.io/#https://github.com/friedger/clarity-smart-contracts 
the syntax highlighting does not show up (https://open-vsx.org/extension/lgalabru/clarity-lsp)
but then adding the extension below allows the highlighting to show up:
(https://open-vsx.org/extension/blockstack/clarity)
Is it possible to combine both into just one .vsix extension?

**Comment by lgalabru** [comment]
Thank you for reporting this @fluidvoice! Yeah I think we should definitely absorb the clarity syntax definition in this project.
Want to take a crack at this? Happy to provide some support on Discord - just DM me :).

**Comment by fluidvoice** [comment]
> Thank you for reporting this @fluidvoice! Yeah I think we should definitely absorb the clarity syntax definition in this project.
> Want to take a crack at this? Happy to provide some support on Discord - just DM me :).

OK, might take a look. btw, you should claim ownership of the extension here:

[![imgur pic](https://imgur.com/r9VuxYW.png "imgur")](https://open-vsx.org/extension/lgalabru/clarity-lsp)

**Comment by fluidvoice** [comment]
https://discord.com/channels/621759717756370964/713087894260023377/726399215109931048

**Comment by lgalabru** [comment]
Color highlights is currently not in the scope of this project. The extension https://open-vsx.org/extension/blockstack/clarity is in charge of providing this feature, it was broken but I'm pretty it has recently been fixed.
Closing this issue
