### ISSUE TITLE
Error is being shown on wrong line

### ISSUE THREAD

**Issue by hstove** [lgalabru/clarity-lsp#6]
See this screenshot for details. Error is on line 36, and the type error from Clarity also indicates line 36. However, the error always shows up on line 37, as you can see in the screenshot. The error message is correct (type error in `+`).

![image](https://user-images.githubusercontent.com/1109058/78566934-c62f9280-77d4-11ea-8323-f519ab5c8b9d.png)

**Comment by lgalabru** [comment]
Thank you for reporting this issue @hstove!
This issue is being addressed with the latest release (2.11) available on visual studio marketplace.
Changelog available here: https://github.com/lgalabru/clarity-lsp/compare/2020-04-06...2020-04-07
